// Do not modify manually, this file is generated by the export_deployments_addresses script
export const BRIDGES_ADDRESSES = {
  erc20: {
    yarTest: "0xFeFA9db28299b4bb018B9b174a2B65B9E43542B4",

    polygonTest: "0x09Cfcb106719B7dfC819ABA6d06a3CD06d25e243",
  
    binanceTest: "0x5ed204fc058a75204b0f2C52204821158d66fffB",
  
    ethereumTest: "0x3391F010bEc9F50Fd5A299e5C0e8Bb92De8385A6",
  
    chaosSkaleTest: "0xd208b49b79eAcaCd8f2a045a301A24Cb44317dA4",

    optimismTest: "0xF6a282248CBCC05c992065601B1a2Bb66551bd5A",
    
    arbitrumTest: "0x12247504A16C9fEFbb0819855C06a75c6F16cE6e",
    
    avaxTest: "0xC6A4bED05AAc978e03CD2a395771eE4D5ad0B88a",
    
    baseTest: "0x3ee25242b06Fc4547443413d738cBf17719a7F7D",
  },
  erc721: {
    yarTest: "0x625Ddc123B786c75344fB0C9901dc83BE8A358e2",

    polygonTest: "0xDB0905f9C2Eae6d01476538707f3B405F9A927E3",
  
    binanceTest: "0x1E7a5CD603f6C8eE8cf94A5b3cABbe43a0323C40",
  
    ethereumTest: "0x16293dcBF0A1d01456d6AF735D98E9c30104A776",
  
    chaosSkaleTest: "0xfedD09d2bd511FE88DF7420a5Cdb23097Ae9cB8E",

    optimismTest: "0x87f841583e917ba58a0936aeAA8cFf263e746fbe",
    
    arbitrumTest: "0x96418856c4880E8d3C4b5A8CCA0dBd3771fE6673",
    
    avaxTest: "0x1A2e898302A41E794D84dB585437996a425d9845",
    
    baseTest: "0x0342C41e5e914556aB9686157A81e9744dc55b8F",
  },
  erc1155: {
    yarTest: "0xe75185eB9D57f0Dd3a19CDD503238824aBef7212",

    polygonTest: "0xb87257710929aED5A10d111e7621672E397B2F85",
  
    binanceTest: "0x79daC5DdB3C2D0D9A1B4DA5df6A2aE8dc671F4f4",
  
    ethereumTest: "0x179BA49f52704f719217fAC7C0BAd23131C2f166",
  
    chaosSkaleTest: "0x7A8ae30F79481EEa18C43E7b2340EA1EA44AbB41",

    optimismTest: "0x8101Cc33218a2024384e779b14CF5f9e526Aed7f",
    
    arbitrumTest: "0x043c8F4e6111860AF97f2Eea991Bc6101DE62d13",
    
    avaxTest: "0x2f269013e3B1C801Dff8B3b1BeCa4F55C36a61B1",
    
    baseTest: "0x73ca03153929c0dC7E7204635D06d7Fe5b1576f6",
  },
 };