// Do not modify manually, this file is generated by the export_deployments_addresses script
export const BRIDGES_ADDRESSES = {
  erc20: {
    yarTest: "0x3739B5D0Fd80cC12AcbEA36bAbAF063Cee8A7924",

    polygonTest: "0x8134c3cf23d253e65443ce5a4287eb4ec8686ba0",
  
    binanceTest: "0x01169C9679B9A667B21593eF461df40Ea72C9437",
  
    ethereumTest: "0xc491672e8196a9724E588aa8B6950FD698d3A398",
  
    chaosSkaleTest: "0xf668dc2B9A5a156bdb91092DcAd65aD5Db7D1287",
  },
  erc721: {
    yarTest: "0xda53B08F0B71924cbeDb6d8f610db7F2EE2584cE",

    polygonTest: "0xF625fa80586c73aB194197F0cF3a9184B7556d27",
  
    binanceTest: "0x6DA238d7eAEaB9222401F45B89aA55129631cEa0",
  
    ethereumTest: "0x875D36f0A053E6e2B7FeBC1E1FcCC01F18934f20",
  
    chaosSkaleTest: "0xD8ccE151118821c574F0e4FDD3aB9f3D3135181f",
  },
  erc1155: {
    yarTest: "0xFeFA9db28299b4bb018B9b174a2B65B9E43542B4",

    polygonTest: "0xB6fB34226340FE80c7B9176569abe97043f8ca6e",
  
    binanceTest: "0x1f9e5448bbF4b25B5Cf4f91DD78F45b859E6a9e3",
  
    ethereumTest: "0xa75632616b27b63Aaf16ede13598131C16Ba306f",
  
    chaosSkaleTest: "0xb59Af8Ebdc10a5A7FbbE783678da576CCaa3c76E",
  },
 };