// Do not modify manually, this file is generated by the export_deployments_addresses script
export const BRIDGES_ADDRESSES = {
  erc20: {
    yarTest: "0x3739B5D0Fd80cC12AcbEA36bAbAF063Cee8A7924",

    polygonTest: "0x8134c3cf23d253e65443ce5a4287eb4ec8686ba0",
  
    binanceTest: "0x01169C9679B9A667B21593eF461df40Ea72C9437",
  
    ethereumTest: "0xc491672e8196a9724E588aa8B6950FD698d3A398",
  
    chaosSkaleTest: "0xf668dc2B9A5a156bdb91092DcAd65aD5Db7D1287",
  },
  erc721: {
    yarTest: "0xadbCc487A9723e179dEDAEfd323d4371AAE34b8C",

    polygonTest: "0x5985BF09878BE2fA120Fa9b96BBD31e1994EB24b",
  
    binanceTest: "0x7587cF085212da6B77F52f97079db8dc96b8873b",
  
    ethereumTest: "0x602AC8d56Fc88d90Fe24D8F12348e02E9Fe8d575",
  
    chaosSkaleTest: "0xfedD09d2bd511FE88DF7420a5Cdb23097Ae9cB8E",
  },
  erc1155: {
    yarTest: "0xd28f62d3f725eB2CE96A06031d7e7174F8D28dCC",

    polygonTest: "0x43d48be3fb541AD42cF1C5004C6Df360bA157AD5",
  
    binanceTest: "0x93b491367002f7B71a6C283B43047EbF8c1a4462",
  
    ethereumTest: "0xA9729e5A6C1a12729945456E82e67164Dc395e29",
  
    chaosSkaleTest: "0x57f304Ca28432F18363A49002F62118b8e8fDa11",
  },
 };